[general]
shuffle_caption = false
caption_extension = '.txt'
keep_tokens = 1

[[datasets]]
resolution = 512
batch_size = 1
keep_tokens = 1

  [[datasets.subsets]]
  image_dir = '/home/fangg/other/tts/fluxgym/datasets/mylora'
  class_tokens = 'mylora'
  num_repeats = 10
